### ISSUE TITLE
inconsistence in cc:preconj relation

### ISSUE THREAD

**Issue by rueter** [UniversalDependencies/UD_Finnish#2]
Hi! Appreciate your work and am using it to better understand what needs to be done for Erzya.

http://universaldependencies.org/fi/dep/cc-preconj.html

There is a problem with first example and subsequent Finnish UD example. Both are illustrated with the 
sekä X että Y construction
In the first example both "sekä" and "että" have a relation with X.
I was expecting the word "että" to have a "cc" relation with Y.

**Comment by jmnybl** [comment]
Hi,
That cc-preconj documentation page still contains UD v1 documentation. In v2 documentation "että" should have "cc" relation with Y, you are correct. Was this your problem, or did you found also inconsistencies from the actual data?

The Finnish v2 documentation is waiting for the universal v2 documentation, which will change the language-specific documentation a lot, and we will not update the Finnish pages before the universal documentation is ready.

**Comment by dan-zeman** [comment]
The upper example where both conjunctions are attached to X has been added manually as part of the documentation, but, as the yellow banner warns, this is still the documentation of UD v1.

On the other hand, the examples at the bottom of the page (under the header "Treebank Statistics") are taken from real data, which, as of now, is UD v2.

**Comment by rueter** [comment]
Thank you both for the answer.
I wanted to report the problem on the page. Hopefully, the UD will get updated soon, so you can do your work, too.
:)
